AWSTemplateFormatVersion: '2010-09-09'
Description: SNS Topic for Auto Scaling Group notifications

Parameters:
  NotificationEmail:
    Type: String
    Default: nayanyeole0517@gmail.com
    Description: Email to receive Auto Scaling notifications

Resources:
  # SNS Topic for ASG notifications
  ASGSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: asg-instance-alerts

  # Email subscription to the SNS Topic
  ASGSNSSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ASGSNSTopic
      Protocol: email
      Endpoint: !Ref NotificationEmail

Outputs:
  SNSTopicArn:
    Description: ARN of the SNS Topic for ASG notifications
    Value: !Ref ASGSNSTopic